// <auto-generated />
using EasyDesk.CleanArchitecture.Dal.EfCore.Sagas;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EasyDesk.CleanArchitecture.Dal.PostgreSql.Migrations.Sagas;

[DbContext(typeof(SagasContext))]
[Migration("20260514161133_RemoveMultitenancy")]
partial class RemoveMultitenancy
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("sagas")
            .HasAnnotation("ProductVersion", "10.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("EasyDesk.CleanArchitecture.Dal.EfCore.Sagas.SagaModel", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("text");

                b.Property<string>("Type")
                    .HasMaxLength(2048)
                    .HasColumnType("character varying(2048)");

                b.Property<string>("State")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<byte[]>("State_Old")
                    .IsRequired()
                    .HasColumnType("bytea");

                b.Property<int?>("Version")
                    .HasColumnType("integer");

                b.HasKey("Id", "Type");

                b.ToTable("Sagas", "sagas");
            });
#pragma warning restore 612, 618
    }
}
