// <auto-generated />
using EasyDesk.CleanArchitecture.Dal.EfCore.Messaging;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EasyDesk.CleanArchitecture.Dal.PostgreSql.Migrations.Messaging;

[DbContext(typeof(MessagingContext))]
[Migration("20250516084546_AddInstantToInbox")]
partial class AddInstantToInbox
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("messaging")
            .HasAnnotation("ProductVersion", "9.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("EasyDesk.CleanArchitecture.Dal.EfCore.Messaging.InboxMessage", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("text");

                b.Property<Instant>("Instant")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.ToTable("Inbox", "messaging");
            });

        modelBuilder.Entity("EasyDesk.CleanArchitecture.Dal.EfCore.Messaging.OutboxMessage", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<byte[]>("Content")
                    .IsRequired()
                    .HasColumnType("bytea");

                b.Property<string>("DestinationAddress")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Headers")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<byte[]>("Headers_Old")
                    .IsRequired()
                    .HasColumnType("bytea");

                b.HasKey("Id");

                b.ToTable("Outbox", "messaging");
            });
#pragma warning restore 612, 618
    }
}
