version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-minor, version-update:semver-patch]
    labels:
      - ci
      - dependency

  - package-ecosystem: nuget
    directory: /sample/EasyDesk.SampleApp.Application
    schedule:
      interval: daily
    labels:
      - dependency
    open-pull-requests-limit: 0 # no limit

  - package-ecosystem: nuget
    directory: /sample/EasyDesk.SampleApp.Domain
    schedule:
      interval: daily
    labels:
      - dependency
    open-pull-requests-limit: 0 # no limit

  - package-ecosystem: nuget
    directory: /sample/EasyDesk.SampleApp.Infrastructure
    schedule:
      interval: daily
    labels:
      - dependency
    open-pull-requests-limit: 0 # no limit

  - package-ecosystem: nuget
    directory: /sample/EasyDesk.SampleApp.Web
    schedule:
      interval: daily
    labels:
      - dependency
    open-pull-requests-limit: 0 # no limit

  - package-ecosystem: nuget
    directory: /src/EasyDesk.CleanArchitecture.Application
    schedule:
      interval: daily
    labels:
      - dependency
    open-pull-requests-limit: 0 # no limit

  - package-ecosystem: nuget
    directory: /src/EasyDesk.CleanArchitecture.Dal.EfCore
    schedule:
      interval: daily
    labels:
      - dependency
    open-pull-requests-limit: 0 # no limit

  - package-ecosystem: nuget
    directory: /src/EasyDesk.CleanArchitecture.Dal.PostgreSql
    schedule:
      interval: daily
    labels:
      - dependency
    open-pull-requests-limit: 0 # no limit

  - package-ecosystem: nuget
    directory: /src/EasyDesk.CleanArchitecture.Dal.SqlServer
    schedule:
      interval: daily
    labels:
      - dependency
    open-pull-requests-limit: 0 # no limit

  - package-ecosystem: nuget
    directory: /src/EasyDesk.CleanArchitecture.DependencyInjection
    schedule:
      interval: daily
    labels:
      - dependency
    open-pull-requests-limit: 0 # no limit

  - package-ecosystem: nuget
    directory: /src/EasyDesk.CleanArchitecture.Domain
    schedule:
      interval: daily
    labels:
      - dependency
    open-pull-requests-limit: 0 # no limit

  - package-ecosystem: nuget
    directory: /src/EasyDesk.CleanArchitecture.Infrastructure
    schedule:
      interval: daily
    labels:
      - dependency
    open-pull-requests-limit: 0 # no limit

  - package-ecosystem: nuget
    directory: /src/EasyDesk.CleanArchitecture.Testing.Integration
    schedule:
      interval: daily
    labels:
      - dependency
    open-pull-requests-limit: 0 # no limit

  - package-ecosystem: nuget
    directory: /src/EasyDesk.CleanArchitecture.Testing.Unit
    schedule:
      interval: daily
    labels:
      - dependency
    open-pull-requests-limit: 0 # no limit

  - package-ecosystem: nuget
    directory: /src/EasyDesk.CleanArchitecture.Web
    schedule:
      interval: daily
    labels:
      - dependency
    open-pull-requests-limit: 0 # no limit

  - package-ecosystem: nuget
    directory: /test/EasyDesk.CleanArchitecture.IntegrationTests
    schedule:
      interval: daily
    labels:
      - dependency
    open-pull-requests-limit: 0 # no limit

  - package-ecosystem: nuget
    directory: /test/EasyDesk.CleanArchitecture.UnitTests
    schedule:
      interval: daily
    labels:
      - dependency
    open-pull-requests-limit: 0 # no limit
