version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-minor, version-update:semver-patch]
    labels:
      - ci
      - dependency
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: daily
    labels:
      - dependency
    open-pull-requests-limit: 0 # no limit
