version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3.9-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmqvolume:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:alpine3.16
    environment:
      POSTGRES_USER: sample
      POSTGRES_PASSWORD: samplepass-123
      POSTGRES_DB: sampledb
    volumes:
      - postgresvolume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  rabbitmqvolume:
  postgresvolume: