// <auto-generated />
using EasyDesk.CleanArchitecture.Dal.EfCore.Sagas;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyDesk.CleanArchitecture.Dal.Sqlite.Migrations.Sagas;

[DbContext(typeof(SagasContext))]
[Migration("20250813103200_InitialSchema")]
partial class InitialSchema
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("sagas")
            .HasAnnotation("ProductVersion", "9.0.8");

        modelBuilder.Entity("EasyDesk.CleanArchitecture.Dal.EfCore.Sagas.SagaModel", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("TEXT");

                b.Property<string>("Type")
                    .HasMaxLength(2048)
                    .HasColumnType("TEXT");

                b.Property<string>("Tenant")
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("State")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<byte[]>("State_Old")
                    .IsRequired()
                    .HasColumnType("BLOB");

                b.Property<int?>("Version")
                    .HasColumnType("INTEGER");

                b.HasKey("Id", "Type", "Tenant");

                b.HasIndex("Tenant");

                b.ToTable("Sagas", "sagas");
            });
#pragma warning restore 612, 618
    }
}
