// <auto-generated />
using EasyDesk.CleanArchitecture.Dal.EfCore.Auditing;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyDesk.CleanArchitecture.Dal.Sqlite.Migrations.Auditing;

[DbContext(typeof(AuditingContext))]
partial class AuditingContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("audit")
            .HasAnnotation("ProductVersion", "9.0.8");

        modelBuilder.Entity("EasyDesk.CleanArchitecture.Dal.EfCore.Auditing.Model.AuditRecordModel", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Description")
                    .HasColumnType("TEXT");

                b.Property<string>("Instant")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(2048)
                    .HasColumnType("TEXT");

                b.Property<bool>("Success")
                    .HasColumnType("INTEGER");

                b.Property<string>("Tenant")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<int>("Type")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("Instant")
                    .IsDescending();

                b.HasIndex("Tenant");

                b.ToTable("AuditRecords", "audit");
            });

        modelBuilder.Entity("EasyDesk.CleanArchitecture.Dal.EfCore.Auditing.Model.AuditRecordModel", b =>
            {
                b.OwnsMany("EasyDesk.CleanArchitecture.Dal.EfCore.Auditing.Model.AuditIdentityModel", "Identities", b1 =>
                    {
                        b1.Property<long>("AuditRecordId")
                            .HasColumnType("INTEGER");

                        b1.Property<string>("IdentityRealm")
                            .HasColumnType("TEXT");

                        b1.Property<string>("Identity")
                            .IsRequired()
                            .HasMaxLength(1024)
                            .HasColumnType("TEXT");

                        b1.HasKey("AuditRecordId", "IdentityRealm");

                        b1.ToTable("AuditIdentities", "audit");

                        b1.WithOwner()
                            .HasForeignKey("AuditRecordId");

                        b1.OwnsMany("EasyDesk.CleanArchitecture.Dal.EfCore.Auditing.Model.AuditIdentityAttributeModel", "IdentityAttributes", b2 =>
                            {
                                b2.Property<long>("AuditRecordId")
                                    .HasColumnType("INTEGER");

                                b2.Property<string>("Realm")
                                    .HasColumnType("TEXT");

                                b2.Property<string>("Key")
                                    .HasColumnType("TEXT");

                                b2.Property<string>("Value")
                                    .HasColumnType("TEXT");

                                b2.HasKey("AuditRecordId", "Realm", "Key", "Value");

                                b2.ToTable("AuditIdentityAttributes", "audit");

                                b2.WithOwner()
                                    .HasForeignKey("AuditRecordId", "Realm");
                            });

                        b1.Navigation("IdentityAttributes");
                    });

                b.OwnsMany("EasyDesk.CleanArchitecture.Dal.EfCore.Auditing.Model.AuditRecordPropertyModel", "Properties", b1 =>
                    {
                        b1.Property<long>("AuditRecordId")
                            .HasColumnType("INTEGER");

                        b1.Property<string>("Key")
                            .HasColumnType("TEXT");

                        b1.Property<string>("Value")
                            .HasColumnType("TEXT");

                        b1.HasKey("AuditRecordId", "Key", "Value");

                        b1.ToTable("AuditProperties", "audit");

                        b1.WithOwner()
                            .HasForeignKey("AuditRecordId");
                    });

                b.Navigation("Identities");

                b.Navigation("Properties");
            });
#pragma warning restore 612, 618
    }
}
