// <auto-generated />
using System;
using EasyDesk.CleanArchitecture.Dal.EfCore.Auditing;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyDesk.CleanArchitecture.Dal.SqlServer.Migrations.Auditing;

[DbContext(typeof(AuditingContext))]
[Migration("20230407154356_AddProperties")]
partial class AddProperties
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("audit")
            .HasAnnotation("ProductVersion", "7.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("EasyDesk.CleanArchitecture.Dal.EfCore.Auditing.Model.AuditRecordModel", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("Instant")
                    .HasColumnType("datetime2");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("Success")
                    .HasColumnType("bit");

                b.Property<string>("TenantId")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<int>("Type")
                    .HasColumnType("int");

                b.Property<string>("UserId")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("Instant")
                    .IsDescending();

                b.HasIndex("TenantId");

                b.ToTable("AuditRecords", "audit");
            });

        modelBuilder.Entity("EasyDesk.CleanArchitecture.Dal.EfCore.Auditing.Model.AuditRecordModel", b =>
            {
                b.OwnsMany("EasyDesk.CleanArchitecture.Dal.EfCore.Auditing.Model.AuditRecordPropertyModel", "Properties", b1 =>
                    {
                        b1.Property<long>("AuditRecordId")
                            .HasColumnType("bigint");

                        b1.Property<string>("Key")
                            .HasColumnType("nvarchar(450)");

                        b1.Property<string>("Value")
                            .IsRequired()
                            .HasColumnType("nvarchar(max)");

                        b1.HasKey("AuditRecordId", "Key");

                        b1.ToTable("AuditRecordPropertyModel", "audit");

                        b1.WithOwner()
                            .HasForeignKey("AuditRecordId");
                    });

                b.Navigation("Properties");
            });
#pragma warning restore 612, 618
    }
}
