// <auto-generated />
using System;
using EasyDesk.CleanArchitecture.Dal.EfCore.Auditing;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyDesk.CleanArchitecture.Dal.SqlServer.Migrations.Auditing;

[DbContext(typeof(AuditingContext))]
partial class AuditingContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("audit")
            .HasAnnotation("ProductVersion", "7.0.7")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("EasyDesk.CleanArchitecture.Dal.EfCore.Auditing.Model.AuditRecordModel", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("Instant")
                    .HasColumnType("datetime2");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(2048)
                    .HasColumnType("nvarchar(2048)");

                b.Property<bool>("Success")
                    .HasColumnType("bit");

                b.Property<string>("Tenant")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<int>("Type")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("Instant")
                    .IsDescending();

                b.HasIndex("Tenant");

                b.ToTable("AuditRecords", "audit");
            });

        modelBuilder.Entity("EasyDesk.CleanArchitecture.Dal.EfCore.Auditing.Model.AuditRecordModel", b =>
            {
                b.OwnsMany("EasyDesk.CleanArchitecture.Dal.EfCore.Auditing.Model.AuditIdentityModel", "Identities", b1 =>
                    {
                        b1.Property<long>("AuditRecordId")
                            .HasColumnType("bigint");

                        b1.Property<string>("Realm")
                            .HasColumnType("nvarchar(450)");

                        b1.Property<string>("Identity")
                            .IsRequired()
                            .HasMaxLength(1024)
                            .HasColumnType("nvarchar(1024)");

                        b1.HasKey("AuditRecordId", "Realm");

                        b1.ToTable("AuditIdentities", "audit");

                        b1.WithOwner()
                            .HasForeignKey("AuditRecordId");

                        b1.OwnsMany("EasyDesk.CleanArchitecture.Dal.EfCore.Auditing.Model.AuditIdentityAttributeModel", "IdentityAttributes", b2 =>
                            {
                                b2.Property<long>("AuditRecordId")
                                    .HasColumnType("bigint");

                                b2.Property<string>("Realm")
                                    .HasColumnType("nvarchar(450)");

                                b2.Property<string>("Key")
                                    .HasColumnType("nvarchar(450)");

                                b2.Property<string>("Value")
                                    .HasColumnType("nvarchar(450)");

                                b2.HasKey("AuditRecordId", "Realm", "Key", "Value");

                                b2.ToTable("AuditIdentityAttributes", "audit");

                                b2.WithOwner()
                                    .HasForeignKey("AuditRecordId", "Realm");
                            });

                        b1.Navigation("IdentityAttributes");
                    });

                b.OwnsMany("EasyDesk.CleanArchitecture.Dal.EfCore.Auditing.Model.AuditRecordPropertyModel", "Properties", b1 =>
                    {
                        b1.Property<long>("AuditRecordId")
                            .HasColumnType("bigint");

                        b1.Property<string>("Key")
                            .HasColumnType("nvarchar(450)");

                        b1.Property<string>("Value")
                            .IsRequired()
                            .HasColumnType("nvarchar(max)");

                        b1.HasKey("AuditRecordId", "Key");

                        b1.ToTable("AuditProperties", "audit");

                        b1.WithOwner()
                            .HasForeignKey("AuditRecordId");
                    });

                b.Navigation("Identities");

                b.Navigation("Properties");
            });
#pragma warning restore 612, 618
    }
}
