// <auto-generated />
using System;
using EasyDesk.SampleApp.Infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EasyDesk.SampleApp.Infrastructure.DataAccess.Migrations;

[DbContext(typeof(SampleAppContext))]
partial class SampleAppContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("domain")
            .HasAnnotation("ProductVersion", "7.0.1")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.HasSequence("EntityFrameworkHiLoSequence")
            .IncrementsBy(10);

        modelBuilder.Entity("EasyDesk.SampleApp.Infrastructure.DataAccess.Model.PersonModel", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("CreatedBy")
                    .HasColumnType("text");

                b.Property<LocalDate>("DateOfBirth")
                    .HasColumnType("date");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("boolean");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("TenantId")
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("TenantId");

                b.ToTable("People", "domain");
            });

        modelBuilder.Entity("EasyDesk.SampleApp.Infrastructure.DataAccess.Model.PetModel", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "EntityFrameworkHiLoSequence");

                b.Property<string>("Nickname")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<Guid>("PersonId")
                    .HasColumnType("uuid");

                b.Property<string>("TenantId")
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("PersonId");

                b.HasIndex("TenantId");

                b.ToTable("Pets", "domain");
            });

        modelBuilder.Entity("EasyDesk.SampleApp.Infrastructure.DataAccess.Model.PetModel", b =>
            {
                b.HasOne("EasyDesk.SampleApp.Infrastructure.DataAccess.Model.PersonModel", "Person")
                    .WithMany("Pets")
                    .HasForeignKey("PersonId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Person");
            });

        modelBuilder.Entity("EasyDesk.SampleApp.Infrastructure.DataAccess.Model.PersonModel", b =>
            {
                b.Navigation("Pets");
            });
#pragma warning restore 612, 618
    }
}
