// <auto-generated />
using System;
using EasyDesk.SampleApp.Infrastructure.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyDesk.SampleApp.Infrastructure.EfCore.Migrations.Sqlite;

[DbContext(typeof(SqliteSampleAppContext))]
[Migration("20250813133412_InitialSchema")]
partial class InitialSchema
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("domain")
            .HasAnnotation("ProductVersion", "9.0.8");

        modelBuilder.Entity("EasyDesk.SampleApp.Infrastructure.EfCore.Model.PersonModel", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<bool>("Approved")
                    .HasColumnType("INTEGER");

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("DateOfBirth")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Tenant")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<long>("_Version")
                    .IsConcurrencyToken()
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("Tenant");

                b.ToTable("People", "domain");
            });

        modelBuilder.Entity("EasyDesk.SampleApp.Infrastructure.EfCore.Model.PetModel", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Nickname")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<Guid>("PersonId")
                    .HasColumnType("TEXT");

                b.Property<string>("Tenant")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<long>("_Version")
                    .IsConcurrencyToken()
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("PersonId");

                b.HasIndex("Tenant");

                b.ToTable("Pets", "domain");
            });

        modelBuilder.Entity("EasyDesk.SampleApp.Infrastructure.EfCore.Model.PersonModel", b =>
            {
                b.OwnsOne("EasyDesk.SampleApp.Infrastructure.EfCore.Model.AddressModel", "Residence", b1 =>
                    {
                        b1.Property<Guid>("PersonModelId")
                            .HasColumnType("TEXT");

                        b1.Property<string>("City")
                            .HasMaxLength(100)
                            .HasColumnType("TEXT");

                        b1.Property<string>("Country")
                            .HasMaxLength(100)
                            .HasColumnType("TEXT");

                        b1.Property<string>("District")
                            .HasMaxLength(100)
                            .HasColumnType("TEXT");

                        b1.Property<string>("Province")
                            .HasMaxLength(100)
                            .HasColumnType("TEXT");

                        b1.Property<string>("Region")
                            .HasMaxLength(100)
                            .HasColumnType("TEXT");

                        b1.Property<string>("State")
                            .HasMaxLength(100)
                            .HasColumnType("TEXT");

                        b1.Property<string>("StreetName")
                            .IsRequired()
                            .HasMaxLength(100)
                            .HasColumnType("TEXT");

                        b1.Property<string>("StreetNumber")
                            .HasMaxLength(100)
                            .HasColumnType("TEXT");

                        b1.Property<string>("StreetType")
                            .HasMaxLength(100)
                            .HasColumnType("TEXT");

                        b1.HasKey("PersonModelId");

                        b1.ToTable("People", "domain");

                        b1.WithOwner()
                            .HasForeignKey("PersonModelId");
                    });

                b.Navigation("Residence")
                    .IsRequired();
            });

        modelBuilder.Entity("EasyDesk.SampleApp.Infrastructure.EfCore.Model.PetModel", b =>
            {
                b.HasOne("EasyDesk.SampleApp.Infrastructure.EfCore.Model.PersonModel", "Person")
                    .WithMany("Pets")
                    .HasForeignKey("PersonId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Person");
            });

        modelBuilder.Entity("EasyDesk.SampleApp.Infrastructure.EfCore.Model.PersonModel", b =>
            {
                b.Navigation("Pets");
            });
#pragma warning restore 612, 618
    }
}
