// <auto-generated />
using System;
using EasyDesk.CleanArchitecture.Dal.EfCore.Sagas;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyDesk.CleanArchitecture.Dal.SqlServer.Migrations.Sagas;

[DbContext(typeof(SagasContext))]
[Migration("20230228100744_MakeFieldsNonNullable")]
partial class MakeFieldsNonNullable
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("sagas")
            .HasAnnotation("ProductVersion", "7.0.3")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("EasyDesk.CleanArchitecture.Dal.EfCore.Sagas.SagaModel", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("Type")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("TenantId")
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)")
                    .HasDefaultValue("");

                b.Property<byte[]>("State")
                    .IsRequired()
                    .HasColumnType("varbinary(max)");

                b.Property<int?>("Version")
                    .HasColumnType("int");

                b.HasKey("Id", "Type", "TenantId");

                b.HasIndex("TenantId");

                b.ToTable("Sagas", "sagas");
            });
#pragma warning restore 612, 618
    }
}
