// <auto-generated />
using EasyDesk.CleanArchitecture.Dal.EfCore.Sagas;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EasyDesk.CleanArchitecture.Dal.PostgreSql.Migrations.Sagas;

[DbContext(typeof(SagasContext))]
[Migration("20221229170525_InitialSchema")]
partial class InitialSchema
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("sagas")
            .HasAnnotation("ProductVersion", "7.0.1")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("EasyDesk.CleanArchitecture.Dal.EfCore.Sagas.SagaModel", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("text");

                b.Property<string>("Type")
                    .HasColumnType("text");

                b.Property<string>("TenantId")
                    .HasColumnType("text");

                b.Property<byte[]>("State")
                    .IsRequired()
                    .HasColumnType("bytea");

                b.Property<int>("Version")
                    .HasColumnType("integer");

                b.HasKey("Id", "Type", "TenantId");

                b.HasIndex("TenantId");

                b.ToTable("Sagas", "sagas");
            });
#pragma warning restore 612, 618
    }
}
