name: Continuous Integration

env:
  DOTNET_VERSION: 9.x

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    tags: 
      - "*"

jobs:
  build:
    name: Build & Unit Test
    runs-on: ubuntu-20.04
    env:
      PROJECT_DIRS: |
        src/commons/EasyDesk.Commons
        src/commons/EasyDesk.Extensions.Configuration
        src/commons/EasyDesk.Extensions.DependencyInjection
        src/commons/EasyDesk.Testing
        src/ca/EasyDesk.CleanArchitecture.Domain
        src/ca/EasyDesk.CleanArchitecture.Application
        src/ca/EasyDesk.CleanArchitecture.Infrastructure
        src/ca/EasyDesk.CleanArchitecture.Dal.EfCore
        src/ca/EasyDesk.CleanArchitecture.Dal.SqlServer
        src/ca/EasyDesk.CleanArchitecture.Dal.PostgreSql
        src/ca/EasyDesk.CleanArchitecture.Web
        src/ca/EasyDesk.CleanArchitecture.DependencyInjection
        src/ca/EasyDesk.CleanArchitecture.Testing.Unit
        src/ca/EasyDesk.CleanArchitecture.Testing.Integration
      OUTPUT_DIR: publish
    outputs:
      version: ${{ steps.semver.outputs.version }}
      should-release: ${{ steps.semver.outputs.should-release }}
      is-prerelease: ${{ steps.semver.outputs.is-github-prerelease }}
    steps:
      - id: semver
        name: Checkout
        uses: EasyDesk/action-semver-checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Build
        uses: EasyDesk/action-dotnet-build@v1
        with:
          warnings-as-errors: true
      - name: EasyDesk.Commons Unit Tests
        uses: EasyDesk/action-dotnet-test@v1
        with:
          path: test/commons/EasyDesk.Commons.UnitTests
          test-args: --logger 'GitHubActions'
      - name: EasyDesk.Extensions.Configuration Unit Tests
        uses: EasyDesk/action-dotnet-test@v1
        with:
          path: test/commons/EasyDesk.Extensions.Configuration.UnitTests
          test-args: --logger 'GitHubActions'
      - name: EasyDesk.Testing Unit tests
        uses: EasyDesk/action-dotnet-test@v1
        with:
          path: test/commons/EasyDesk.Testing.UnitTests
          test-args: --logger 'GitHubActions'
      - name: EasyDesk.CleanArchitecture Unit tests
        uses: EasyDesk/action-dotnet-test@v1
        with:
          path: test/ca/EasyDesk.CleanArchitecture.UnitTests
          test-args: --logger 'GitHubActions'
      - name: Pack
        uses: EasyDesk/action-dotnet-pack@v1
        with:
          project-names: ${{ env.PROJECT_DIRS }}
          package-version: ${{ steps.semver.outputs.version }}
          output-dir: ${{ env.OUTPUT_DIR }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: ${{ env.OUTPUT_DIR }}

  test:
    name: Integration Test
    runs-on: ubuntu-20.04
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        db-provider:
          - SqlServer
          - PostgreSql
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Build
        uses: EasyDesk/action-dotnet-build@v1
        with:
          warnings-as-errors: true
      - name: Integration tests (${{ matrix.db-provider }})
        uses: EasyDesk/action-dotnet-test@v1
        env:
          DB_PROVIDER: ${{ matrix.db-provider }}
        with:
          path: test/ca/EasyDesk.CleanArchitecture.IntegrationTests
          test-args: --logger 'GitHubActions'

  command-test:
    name: Command Test
    runs-on: ubuntu-20.04
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        include:
         - db-provider: SqlServer
           sqlserver-connection: "Server=localhost,1433;Initial Catalog=SampleDB;User Id=SA;TrustServerCertificate=True;Password=samplepass.123;"
           usesdb: true
         - db-provider: PostgreSql
           postgres-connection: "Host=localhost;Port=5432;Database=sampledb;Username=sample;Password=samplepass-123;"
           usesdb: true
         - usesdb: false
    env:
      CONNECTIONSTRINGS__SQLSERVER: ${{ matrix.sqlserver-connection }}
      CONNECTIONSTRINGS__POSTGRESQL: ${{ matrix.postgres-connection }}
      CONNECTIONSTRINGS__RABBITMQ: "amqp://admin:admin@localhost:5672"
      DBPROVIDER: ${{ matrix.db-provider || PostgreSql }}
      OUTPUT_DIR: bin/Release
      COMMAND_BASE: dotnet "${OUTPUT_DIR}/EasyDesk.SampleApp.Web.dll"
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        options: --user root
        env:
          ACCEPT_EULA: "Y"
          MSSQL_PID: Developer
          MSSQL_SA_PASSWORD: samplepass.123
        volumes:
          - sqlservervolume:/var/opt/mssql
        ports:
          - 1433:1433
      postgres:
        image: postgres:alpine3.16
        env:
          POSTGRES_USER: sample
          POSTGRES_PASSWORD: samplepass-123
          POSTGRES_DB: sampledb
        volumes:
          - postgresvolume:/var/lib/postgresql/data
        ports:
          - 5432:5432
      rabbitmq:
        image: rabbitmq:3.9-management
        env:
          RABBITMQ_DEFAULT_USER: admin
          RABBITMQ_DEFAULT_PASS: admin
        volumes:
          - rabbitmqvolume:/var/lib/rabbitmq
        ports:
          - 5672:5672
          - 15672:15672
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Build
        uses: EasyDesk/action-dotnet-build@v1
        with:
          path: src/sample/EasyDesk.SampleApp.Web/
          warnings-as-errors: true
          build-configuration: Release
          build-args: -o "${{ env.OUTPUT_DIR }}"
      - name: Migrate
        uses: EasyDesk/action-dotnet@v1
        if: ${{ matrix.usesdb == true }}
        env:
          ASPNETCORE_ENVIRONMENT: Production
        with:
            script: ${{ env.COMMAND_BASE }} -- migrate
      - name: Seeding
        uses: EasyDesk/action-dotnet@v1
        if: ${{ matrix.usesdb == true }}
        env:
          ASPNETCORE_ENVIRONMENT: Development
        with:
            script: ${{ env.COMMAND_BASE }} -- seed-dev
      - name: Openapi
        if: ${{ matrix.usesdb == false }}
        uses: EasyDesk/action-dotnet@v1
        env:
          ASPNETCORE_ENVIRONMENT: Production
        with:
            script: ${{ env.COMMAND_BASE }} -- openapi

  release:
    name: GitHub Release
    if: needs.build.outputs.should-release == 'true'
    concurrency: release
    needs: [build, test, command-test]
    runs-on: ubuntu-20.04
    permissions: write-all
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: nuget-package
      - name: Release
        uses: EasyDesk/action-semver-release@v1
        with:
          version: ${{ needs.build.outputs.version }}
          prerelease: ${{ needs.build.outputs.is-prerelease }}
          files: '*.nupkg'

  deploy:
    name: Deploy to NuGet
    needs: [release]
    concurrency: deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: nuget-package
      - name: NuGet library deploy
        uses: EasyDesk/job-nuget-library-deploy@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
