name: Continuous Integration

env:
  DOTNET_VERSION: 6.x

on:
  push:
    branches:
      - "**"
    tags: 
      - "*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    env:
      PROJECT_DIRS: |
        src/EasyDesk.CleanArchitecture.Domain
        src/EasyDesk.CleanArchitecture.Application
        src/EasyDesk.CleanArchitecture.Infrastructure
        src/EasyDesk.CleanArchitecture.Dal.EfCore
        src/EasyDesk.CleanArchitecture.Dal.SqlServer
        src/EasyDesk.CleanArchitecture.Dal.PostgreSql
        src/EasyDesk.CleanArchitecture.Web
        src/EasyDesk.CleanArchitecture.DependencyInjection
        src/EasyDesk.CleanArchitecture.Testing.Unit
        src/EasyDesk.CleanArchitecture.Testing.Integration
      OUTPUT_DIR: publish
    outputs:
      version: ${{ steps.semver.outputs.version }}
      should-release: ${{ steps.semver.outputs.should-release }}
      is-prerelease: ${{ steps.semver.outputs.is-github-prerelease }}
    steps:
      - id: semver
        name: Checkout
        uses: EasyDesk/action-semver-checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Build
        uses: EasyDesk/action-dotnet-build@v1
        with:
          warnings-as-errors: true
      - name: Unit tests
        uses: EasyDesk/action-dotnet-test@v1
        with:
          path: test/EasyDesk.CleanArchitecture.UnitTests
      - name: Integration tests
        uses: EasyDesk/action-dotnet-test@v1
        with:
          path: test/EasyDesk.CleanArchitecture.IntegrationTests
      - name: Pack
        uses: EasyDesk/action-dotnet-pack@v1
        with:
          project-names: ${{ env.PROJECT_DIRS }}
          package-version: ${{ steps.semver.outputs.version }}
          output-dir: ${{ env.OUTPUT_DIR }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nuget-package
          path: ${{ env.OUTPUT_DIR }}
  release:
    name: GitHub Release
    if: needs.build.outputs.should-release == 'true'
    concurrency: release
    needs: [build]
    runs-on: ubuntu-20.04
    permissions: write-all
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: nuget-package
      - name: Release
        uses: EasyDesk/action-semver-release@v1
        with:
          version: ${{ needs.build.outputs.version }}
          prerelease: ${{ needs.build.outputs.is-prerelease }}
          files: '*.nupkg'
  deploy:
    name: Deploy to NuGet
    needs: [release]
    concurrency: deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: nuget-package
      - name: NuGet library deploy
        uses: EasyDesk/job-nuget-library-deploy@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
